# Generated by Django 6.0.6 on 2026-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0003_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resume", "職歴書・履歴書"),
                    ("manual", "マニュアル・操作手順"),
                    ("policy", "規程・ポリシー"),
                    ("technical", "技術資料"),
                    ("report", "レポート・報告書"),
                    ("other", "その他"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
