# Generated by Django 6.0.6 on 2026-06-18 18:42

import knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0004_document_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=knowledge_base.models._pdf_upload_path
            ),
        ),
    ]
